services:

  livefetcher:
    build:
      context: .
      dockerfile: $DOCKERFILE
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 9999:9999
      - 2113:2113
    platform: linux/amd64
    volumes:
      - ./logs:/livefetcher/logs
    deploy:
      restart_policy:
        condition: on-failure
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    logging:
      driver: none
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    logging:
      driver: none

  db:
    image: postgis/postgis:16-3.4
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_GRAFANA_USER}:${POSTGRES_GRAFANA_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    links:
      - db
      - prometheus
    logging:
      driver: none

volumes:
  db-data:
    driver: local
  grafana: