services:

  livefetcher:
    build:
      context: .
      dockerfile: $DOCKERFILE
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - 9999:9999
      - 2113:2113
    platform: linux/amd64
    volumes:
      - ./logs:/livefetcher/logs
    deploy:
      restart_policy:
        condition: on-failure
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    logging:
      driver: none
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    logging:
      driver: none

  db:
    image: postgis/postgis:16-3.4
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    
  redis:
    image: redis:7.2.5-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - 6379:6379
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_GRAFANA_USER}:${POSTGRES_GRAFANA_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    links:
      - db
      - prometheus
    logging:
      driver: none

volumes:
  db-data:
    driver: local
  grafana: