-- +migrate Up
ALTER TABLE lives ALTER COLUMN starttime TYPE TIMESTAMP(0) WITH TIME ZONE;
ALTER TABLE lives ALTER COLUMN opentime TYPE TIMESTAMP(0) WITH TIME ZONE;
-- +migrate Down
ALTER TABLE lives ALTER COLUMN starttime TYPE TIMESTAMP(0);
ALTER TABLE lives ALTER COLUMN opentime TYPE TIMESTAMP(0);